import { test } from 'node:test';
import assert from 'node:assert/strict';
import * as fs from 'node:fs/promises';
import path from 'node:path';
import { randomUUID } from 'node:crypto';
import { ProjectService } from '../src/main/project-service.ts';
import { CompileService } from '../src/main/compile-service.ts';
import { digest } from '../src/main/files.ts';
import { reviewSchema } from '../src/shared/contracts.ts';
import { changedText, proposalChanges } from '../src/shared/review.ts';

test('actual source, candidate package, PDF preservation and dependency invalidation', { timeout: 60000 }, async () => {
  const root = path.resolve('.test-runs', 'compile-' + randomUUID()), paper = path.join(root, 'paper with spaces');
  await fs.mkdir(path.join(paper, '.modern-editor'), { recursive: true });
  await fs.copyFile('fixtures/sample/main.tex', path.join(paper, 'main.tex'));
  await fs.copyFile('fixtures/sample/review.json', path.join(paper, '.modern-editor/review.json'));
  const projects = new ProjectService(path.join(root, 'cache')), project = await projects.open(path.join(paper, 'main.tex'));
  const compiler = new CompileService(projects, path.join(root, 'builds'));
  const baseline = await compiler.compile(project.id, project.text, 'pdflatex');
  assert.equal(baseline.success, true, baseline.log); assert.equal(baseline.clean, true);
  const goodBytes = await compiler.pdf(baseline.id), hash = digest(goodBytes);
  assert.equal(Buffer.from(goodBytes.subarray(0, 5)).toString(), '%PDF-');
  const review = reviewSchema.parse(JSON.parse(await fs.readFile('fixtures/sample/review.json', 'utf8'))), c = review.comments.find(c => c.id === 'c4')!;
  const candidate = changedText(project.text, proposalChanges(project.text, c));
  const accepted = await compiler.compile(project.id, candidate, 'pdflatex');
  assert.equal(accepted.clean, true, accepted.log); assert.equal(await compiler.validate(project.id, accepted.id, candidate), true);
  const missing = await compiler.compile(project.id, candidate.replace('\\usepackage{mathtools}\n', ''), 'pdflatex');
  assert.equal(missing.success, false);
  const broken = await compiler.compile(project.id, project.text.replace('\\end{document}', '\\unknownCommand\n\\end{document}'), 'pdflatex');
  assert.equal(broken.success, false); assert.equal(digest(await compiler.pdf(baseline.id)), hash);
  assert.equal(await fs.readFile(project.path, 'utf8'), project.text);
  assert.equal(await compiler.validate(project.id, accepted.id, candidate + '\n'), false);
  await fs.writeFile(path.join(paper, 'extra.tex'), 'Original dependency');
  const withDependency = await compiler.compile(project.id, project.text, 'pdflatex');
  await fs.writeFile(path.join(paper, 'extra.tex'), 'Changed dependency');
  assert.equal(await compiler.validate(project.id, withDependency.id, project.text), false);
  await fs.mkdir('test-evidence', { recursive: true });
  await fs.writeFile('test-evidence/compiled-sample.pdf', await compiler.pdf(accepted.id));
  await fs.writeFile('test-evidence/compile-results.json', JSON.stringify({ passed: true, root, baseline, accepted, missing, broken, preservedSource: true, preservedPdf: true, changedDependencyInvalidated: true }, null, 2));
});
