import { contextBridge, ipcRenderer } from 'electron';
import type { EditorAPI } from '../shared/contracts.ts';
const api: EditorAPI = {
  openProject: () => ipcRenderer.invoke('project:open'),
  resumeProject: () => ipcRenderer.invoke('project:resume'),
  openDemo: () => ipcRenderer.invoke('project:demo'),
  openDraft: () => ipcRenderer.invoke('project:draft'),
  exportSource: input => ipcRenderer.invoke('source:export', input),
  inspectRecovery: () => ipcRenderer.invoke('source:recover'),
  persist: input => ipcRenderer.invoke('project:persist', input),
  save: input => ipcRenderer.invoke('project:save', input),
  setEngine: (projectId, engine) => ipcRenderer.invoke('project:engine', { projectId, engine }),
  setEffort: (projectId, effort) => ipcRenderer.invoke('project:effort', { projectId, effort }),
  setFastMode: (projectId, fastMode) => ipcRenderer.invoke('project:fast-mode', { projectId, fastMode }),
  setPaperInstructions: (projectId, instructions) => ipcRenderer.invoke('project:instructions', { projectId, instructions }),
  setWorkspace: (projectId, workspace) => ipcRenderer.invoke('project:workspace', { projectId, workspace }),
  pinBaseline: input => ipcRenderer.invoke('comparison:pin', input),
  chooseBaseline: id => ipcRenderer.invoke('comparison:choose', id),
  versionHistory: projectId => ipcRenderer.invoke('comparison:history', projectId),
  compareSavedVersion: (projectId, versionId) => ipcRenderer.invoke('comparison:saved', { projectId, versionId }),
  deleteSavedVersion: (projectId, versionId) => ipcRenderer.invoke('comparison:delete', { projectId, versionId }),
  setHistoryBudget: (projectId, bytes) => ipcRenderer.invoke('comparison:budget', { projectId, bytes }),
  reload: id => ipcRenderer.invoke('project:reload', id),
  importReview: (id, text) => ipcRenderer.invoke('review:import', { projectId: id, text }),
  compile: input => ipcRenderer.invoke('build:compile', input),
  validateBuild: input => ipcRenderer.invoke('build:validate', input),
  getPdf: id => ipcRenderer.invoke('build:pdf', id),
  locatePdf: input => ipcRenderer.invoke('build:locate', input),
  cancelBuild: () => ipcRenderer.invoke('build:cancel'),
  clearOldBuilds: ids => ipcRenderer.invoke('build:clear-old', ids),
  requestReview: input => ipcRenderer.invoke('codex:review', input),
  replyToComment: input => ipcRenderer.invoke('codex:reply', input),
  waitingResults: id => ipcRenderer.invoke('codex:waiting', id),
  acknowledgeResult: input => ipcRenderer.invoke('codex:acknowledge', input),
  generatePreamble: input => ipcRenderer.invoke('codex:preamble', input),
  cancelCodex: () => ipcRenderer.invoke('codex:cancel'),
  onCodexProgress: callback => { const listener = (_: unknown, message: string) => callback(message); ipcRenderer.on('codex:progress', listener); return () => ipcRenderer.removeListener('codex:progress', listener); },
  finishClose: () => ipcRenderer.invoke('window:close-ready'),
  onCloseRequested: callback => { const listener = () => callback(); ipcRenderer.on('window:close-requested', listener); return () => ipcRenderer.removeListener('window:close-requested', listener); },
  onCommand: callback => { const listener = (_: unknown, command: string) => callback(command); ipcRenderer.on('menu:command', listener); return () => ipcRenderer.removeListener('menu:command', listener); }
};
contextBridge.exposeInMainWorld('editor', api);
